language: android
android:
  components:
  - android-26
  - build-tools-26.0.2
  - sys-img-armeabi-v7a-android-26
sudo:false
before_install:
 - chmod +x gradlew
branches:
  only:
  - master
  - FLOW-UI
before_script:
  - echo no | android create avd --force -n test -t android-26
  - emulator -avd android-26 -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
