language: android
android:
  components:
  - android-22
  - android-26
  - build-tools-26.0.2
  - sys-img-armeabi-v7a-android-26
before_install:
 - chmod +x gradlew
install:
 - echo y | sdkmanager 'ndk-bundle'
 - echo y | sdkmanager 'lldb;3.0'
branches:
  only:
  - master
  - FLOW-UI
  - djvu-ui
before_script:
  - android list sdk --extended --no-ui --all
  - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-22,sys-img-x86_64-android-22
  - echo "n" | android create avd --name myandroid22 -t "android-22" --abi "default/armeabi-v7a"
  - emulator -avd myandroid22 -no-audio -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
notifications:
  slack:
    secure: IbzkCYh7lMOqFzuIAMF7p1d3imgIXWewturYxSP7ePJIjJyJWGSLz+T7W8ntzoPZmSuDiA0OcHMGdS3k5hsUd3c6XAXY3aEp9KEN0j7UxQX0fIEnhcpZ2GedfMwwCXe4NDpIIst9yPC6Rkzk8qJEFgXeUA33vIXMf5mrhW0+/WA0OzatvGQk9OSSKsPWpEtJ5dRALqjEwZMXdsDwp1kQosGgGxFU7VgL+JzfPolUk5+axMGuIT0BBS4dpJrGtRJuMoLO4gkLKXrSdGahfyr0v/KVZYA+f8RL3PzZf5gKWdBdUwjbALJgdVQ1U+4/FULMuLoZo3EQel0cBJl6wecNGFtdfPW/qJoEt9AItVRBbSDjY8moBPwWHJ/4S7sCkyep9ghZuuymnZADzh71zW4RMXszc7Q+i1yoDQHuGRQTmlxdBBYeFBTPpxM3s9+Kl6q4KeRh9tzDzXkQG2ykeW5jXdLkbRDYWxXNMGO3oz7UMlPoYhcH10bQRrwakv73DGsFsbNYznZCpLVyirsHm1jdCxMReAcMQdIoMlWu9aq+JjVvV70xzlbNOwSJdU7UKFlIvJHWDfhbuQeKkvLwns8vpspK8RDnIMEegdYfJIQsn81EGMH2th2lXL4hEzTXT/VWk01laLd7RRIX6zQ2Fg0wBgADhwmHihCWb6XCtUotNeo=
