language: android
android:
  components:
  - android-26
  - build-tools-26.0.2
  - sys-img-armeabi-v7a-android-26
before_install:
 - chmod +x gradlew
branches:
  only:
  - master
  - FLOW-UI
before_script:
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:"21 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
