language: android
android:
  components:
  - android-22
  - android-26
  - build-tools-26.0.2
  - sys-img-armeabi-v7a-android-26
before_install:
 - chmod +x gradlew
branches:
  only:
  - master
  - FLOW-UI
before_script:
  - android list sdk --extended --no-ui --all
  - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-22,sys-img-x86_64-android-22
  - echo "n" | android create avd --name myandroid22 -t "android-22" --abi "default/armeabi-v7a"
  - emulator -avd myandroid22 -no-audio -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
